---
service: my-example-service
language: scala
agents:
  jolokia:
    url: https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=com.jolokia&a=jolokia&v=LATEST
    parameters: host=0.0.0.0,port=8778
components:
  - mariadb-dev
